import type { Shadow } from '~/stores/shadow'

type PresetShadow = Omit<Shadow, 'id'>

interface Preset {
  title: string
  category: 'material' | 'tailwind'
  shadows: PresetShadow[]
}

export const materialDesignPresets: Preset[] = [
  {
    title: 'Elevation 1',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 2,
        x: 0,
        y: 2,
        blur: 1,
        spread: -1,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 1,
        x: 0,
        y: 1,
        blur: 1,
        spread: 0,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 1,
        x: 0,
        y: 1,
        blur: 3,
        spread: 0,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 2',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 3,
        x: 0,
        y: 3,
        blur: 1,
        spread: -2,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 2,
        x: 0,
        y: 2,
        blur: 2,
        spread: 0,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 1,
        x: 0,
        y: 1,
        blur: 5,
        spread: 0,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 3',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 3,
        x: 0,
        y: 3,
        blur: 3,
        spread: -2,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 3,
        x: 0,
        y: 3,
        blur: 4,
        spread: 0,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 1,
        x: 0,
        y: 1,
        blur: 8,
        spread: 0,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 4',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 2,
        x: 0,
        y: 2,
        blur: 4,
        spread: -1,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 4,
        x: 0,
        y: 4,
        blur: 5,
        spread: 0,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 1,
        x: 0,
        y: 1,
        blur: 10,
        spread: 0,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 5',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 3,
        x: 0,
        y: 3,
        blur: 5,
        spread: -1,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 5,
        x: 0,
        y: 5,
        blur: 8,
        spread: 0,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 1,
        x: 0,
        y: 1,
        blur: 14,
        spread: 0,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 6',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 3,
        x: 0,
        y: 3,
        blur: 5,
        spread: -1,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 6,
        x: 0,
        y: 6,
        blur: 10,
        spread: 0,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 1,
        x: 0,
        y: 1,
        blur: 18,
        spread: 0,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 7',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 4,
        x: 0,
        y: 4,
        blur: 5,
        spread: -2,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 7,
        x: 0,
        y: 7,
        blur: 10,
        spread: 1,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 2,
        x: 0,
        y: 2,
        blur: 16,
        spread: 1,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 8',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 5,
        x: 0,
        y: 5,
        blur: 5,
        spread: -3,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 8,
        x: 0,
        y: 8,
        blur: 10,
        spread: 1,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 3,
        x: 0,
        y: 3,
        blur: 14,
        spread: 2,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 9',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 5,
        x: 0,
        y: 5,
        blur: 6,
        spread: -3,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 9,
        x: 0,
        y: 9,
        blur: 12,
        spread: 1,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 3,
        x: 0,
        y: 3,
        blur: 16,
        spread: 2,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 10',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 6,
        x: 0,
        y: 6,
        blur: 6,
        spread: -3,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 10,
        x: 0,
        y: 10,
        blur: 14,
        spread: 1,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 4,
        x: 0,
        y: 4,
        blur: 18,
        spread: 3,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 11',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 6,
        x: 0,
        y: 6,
        blur: 7,
        spread: -4,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 11,
        x: 0,
        y: 11,
        blur: 15,
        spread: 1,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 4,
        x: 0,
        y: 4,
        blur: 20,
        spread: 3,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 12',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 7,
        x: 0,
        y: 7,
        blur: 8,
        spread: -4,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 12,
        x: 0,
        y: 12,
        blur: 17,
        spread: 2,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 5,
        x: 0,
        y: 5,
        blur: 22,
        spread: 4,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 13',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 7,
        x: 0,
        y: 7,
        blur: 8,
        spread: -4,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 13,
        x: 0,
        y: 13,
        blur: 19,
        spread: 2,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 5,
        x: 0,
        y: 5,
        blur: 24,
        spread: 4,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 14',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 7,
        x: 0,
        y: 7,
        blur: 9,
        spread: -4,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 14,
        x: 0,
        y: 14,
        blur: 21,
        spread: 2,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 5,
        x: 0,
        y: 5,
        blur: 26,
        spread: 4,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 15',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 8,
        x: 0,
        y: 8,
        blur: 9,
        spread: -5,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 15,
        x: 0,
        y: 15,
        blur: 22,
        spread: 2,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 6,
        x: 0,
        y: 6,
        blur: 28,
        spread: 5,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 16',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 8,
        x: 0,
        y: 8,
        blur: 10,
        spread: -5,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 16,
        x: 0,
        y: 16,
        blur: 24,
        spread: 2,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 6,
        x: 0,
        y: 6,
        blur: 30,
        spread: 5,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 17',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 8,
        x: 0,
        y: 8,
        blur: 11,
        spread: -5,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 17,
        x: 0,
        y: 17,
        blur: 26,
        spread: 2,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 6,
        x: 0,
        y: 6,
        blur: 32,
        spread: 5,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 18',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 9,
        x: 0,
        y: 9,
        blur: 11,
        spread: -5,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 18,
        x: 0,
        y: 18,
        blur: 28,
        spread: 2,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 7,
        x: 0,
        y: 7,
        blur: 34,
        spread: 6,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 19',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 9,
        x: 0,
        y: 9,
        blur: 12,
        spread: -6,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 19,
        x: 0,
        y: 19,
        blur: 29,
        spread: 2,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 7,
        x: 0,
        y: 7,
        blur: 36,
        spread: 6,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 20',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 10,
        x: 0,
        y: 10,
        blur: 13,
        spread: -6,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 20,
        x: 0,
        y: 20,
        blur: 31,
        spread: 3,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 8,
        x: 0,
        y: 8,
        blur: 38,
        spread: 7,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 21',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 10,
        x: 0,
        y: 10,
        blur: 13,
        spread: -6,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 21,
        x: 0,
        y: 21,
        blur: 33,
        spread: 3,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 8,
        x: 0,
        y: 8,
        blur: 40,
        spread: 7,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 22',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 10,
        x: 0,
        y: 10,
        blur: 14,
        spread: -6,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 22,
        x: 0,
        y: 22,
        blur: 35,
        spread: 3,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 8,
        x: 0,
        y: 8,
        blur: 42,
        spread: 7,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 23',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 11,
        x: 0,
        y: 11,
        blur: 14,
        spread: -7,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 23,
        x: 0,
        y: 23,
        blur: 36,
        spread: 3,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 9,
        x: 0,
        y: 9,
        blur: 44,
        spread: 8,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
  {
    title: 'Elevation 24',
    category: 'material',
    shadows: [
      {
        visible: true,
        angle: 180,
        distance: 11,
        x: 0,
        y: 11,
        blur: 15,
        spread: -7,
        color: '#000000',
        opacity: 20,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 24,
        x: 0,
        y: 24,
        blur: 38,
        spread: 3,
        color: '#000000',
        opacity: 14,
        inset: false,
      },
      {
        visible: true,
        angle: 180,
        distance: 9,
        x: 0,
        y: 9,
        blur: 46,
        spread: 8,
        color: '#000000',
        opacity: 12,
        inset: false,
      },
    ],
  },
]

export const tailwindPresets: Preset[] = [
  {
    title: 'shadow-2xs',
    category: 'tailwind',
    shadows: [
      {
        visible: true,
        angle: 0,
        distance: 1,
        x: 0,
        y: 1,
        blur: 0,
        spread: 0,
        color: '#000000',
        opacity: 5,
        inset: false,
      },
    ],
  },
  {
    title: 'shadow-xs',
    category: 'tailwind',
    shadows: [
      {
        visible: true,
        angle: 0,
        distance: 1,
        x: 0,
        y: 1,
        blur: 2,
        spread: 0,
        color: '#000000',
        opacity: 5,
        inset: false,
      },
    ],
  },
  {
    title: 'shadow-sm',
    category: 'tailwind',
    shadows: [
      {
        visible: true,
        angle: 0,
        distance: 1,
        x: 0,
        y: 1,
        blur: 3,
        spread: 0,
        color: '#000000',
        opacity: 10,
        inset: false,
      },
      {
        visible: true,
        angle: 0,
        distance: 1,
        x: 0,
        y: 1,
        blur: 2,
        spread: -1,
        color: '#000000',
        opacity: 10,
        inset: false,
      },
    ],
  },
  {
    title: 'shadow-md',
    category: 'tailwind',
    shadows: [
      {
        visible: true,
        angle: 0,
        distance: 4,
        x: 0,
        y: 4,
        blur: 6,
        spread: -1,
        color: '#000000',
        opacity: 10,
        inset: false,
      },
      {
        visible: true,
        angle: 0,
        distance: 2,
        x: 0,
        y: 2,
        blur: 4,
        spread: -2,
        color: '#000000',
        opacity: 10,
        inset: false,
      },
    ],
  },
  {
    title: 'shadow-lg',
    category: 'tailwind',
    shadows: [
      {
        visible: true,
        angle: 0,
        distance: 10,
        x: 0,
        y: 10,
        blur: 15,
        spread: -3,
        color: '#000000',
        opacity: 10,
        inset: false,
      },
      {
        visible: true,
        angle: 0,
        distance: 4,
        x: 0,
        y: 4,
        blur: 6,
        spread: -4,
        color: '#000000',
        opacity: 10,
        inset: false,
      },
    ],
  },
  {
    title: 'shadow-xl',
    category: 'tailwind',
    shadows: [
      {
        visible: true,
        angle: 0,
        distance: 20,
        x: 0,
        y: 20,
        blur: 25,
        spread: -5,
        color: '#000000',
        opacity: 10,
        inset: false,
      },
      {
        visible: true,
        angle: 0,
        distance: 8,
        x: 0,
        y: 8,
        blur: 10,
        spread: -6,
        color: '#000000',
        opacity: 10,
        inset: false,
      },
    ],
  },
  {
    title: 'shadow-2xl',
    category: 'tailwind',
    shadows: [
      {
        visible: true,
        angle: 0,
        distance: 25,
        x: 0,
        y: 25,
        blur: 50,
        spread: -12,
        color: '#000000',
        opacity: 25,
        inset: false,
      },
    ],
  },
]

export const allPresets = [...materialDesignPresets, ...tailwindPresets]
